/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyMentorRouteImport } from './routes/apply-mentor'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as MocksAnalysisRouteImport } from './routes/mocks-analysis'
import { Route as PlateauedStrategyRouteImport } from './routes/plateaued-strategy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RankJumpPlanRouteImport } from './routes/rank-jump-plan'
import { Route as StudyDailyRouteImport } from './routes/study-daily'
import { Route as TimeManagementRouteImport } from './routes/time-management'
import { Route as MentorsIndexRouteImport } from './routes/mentors.index'
import { Route as MentorsMentorIdRouteImport } from './routes/mentors.$mentorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyMentorRoute = ApplyMentorRouteImport.update({
  id: '/apply-mentor',
  path: '/apply-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const MocksAnalysisRoute = MocksAnalysisRouteImport.update({
  id: '/mocks-analysis',
  path: '/mocks-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const PlateauedStrategyRoute = PlateauedStrategyRouteImport.update({
  id: '/plateaued-strategy',
  path: '/plateaued-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RankJumpPlanRoute = RankJumpPlanRouteImport.update({
  id: '/rank-jump-plan',
  path: '/rank-jump-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyDailyRoute = StudyDailyRouteImport.update({
  id: '/study-daily',
  path: '/study-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeManagementRoute = TimeManagementRouteImport.update({
  id: '/time-management',
  path: '/time-management',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsIndexRoute = MentorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MentorsRoute,
} as any)
const MentorsMentorIdRoute = MentorsMentorIdRouteImport.update({
  id: '/$mentorId',
  path: '/$mentorId',
  getParentRoute: () => MentorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply-mentor': typeof ApplyMentorRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mentors': typeof MentorsRouteWithChildren
  '/mocks-analysis': typeof MocksAnalysisRoute
  '/plateaued-strategy': typeof PlateauedStrategyRoute
  '/pricing': typeof PricingRoute
  '/rank-jump-plan': typeof RankJumpPlanRoute
  '/study-daily': typeof StudyDailyRoute
  '/time-management': typeof TimeManagementRoute
  '/mentors/$mentorId': typeof MentorsMentorIdRoute
  '/mentors/': typeof MentorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply-mentor': typeof ApplyMentorRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mocks-analysis': typeof MocksAnalysisRoute
  '/plateaued-strategy': typeof PlateauedStrategyRoute
  '/pricing': typeof PricingRoute
  '/rank-jump-plan': typeof RankJumpPlanRoute
  '/study-daily': typeof StudyDailyRoute
  '/time-management': typeof TimeManagementRoute
  '/mentors/$mentorId': typeof MentorsMentorIdRoute
  '/mentors': typeof MentorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply-mentor': typeof ApplyMentorRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mentors': typeof MentorsRouteWithChildren
  '/mocks-analysis': typeof MocksAnalysisRoute
  '/plateaued-strategy': typeof PlateauedStrategyRoute
  '/pricing': typeof PricingRoute
  '/rank-jump-plan': typeof RankJumpPlanRoute
  '/study-daily': typeof StudyDailyRoute
  '/time-management': typeof TimeManagementRoute
  '/mentors/$mentorId': typeof MentorsMentorIdRoute
  '/mentors/': typeof MentorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply-mentor'
    | '/contact'
    | '/how-it-works'
    | '/mentors'
    | '/mocks-analysis'
    | '/plateaued-strategy'
    | '/pricing'
    | '/rank-jump-plan'
    | '/study-daily'
    | '/time-management'
    | '/mentors/$mentorId'
    | '/mentors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply-mentor'
    | '/contact'
    | '/how-it-works'
    | '/mocks-analysis'
    | '/plateaued-strategy'
    | '/pricing'
    | '/rank-jump-plan'
    | '/study-daily'
    | '/time-management'
    | '/mentors/$mentorId'
    | '/mentors'
  id:
    | '__root__'
    | '/'
    | '/apply-mentor'
    | '/contact'
    | '/how-it-works'
    | '/mentors'
    | '/mocks-analysis'
    | '/plateaued-strategy'
    | '/pricing'
    | '/rank-jump-plan'
    | '/study-daily'
    | '/time-management'
    | '/mentors/$mentorId'
    | '/mentors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyMentorRoute: typeof ApplyMentorRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MentorsRoute: typeof MentorsRouteWithChildren
  MocksAnalysisRoute: typeof MocksAnalysisRoute
  PlateauedStrategyRoute: typeof PlateauedStrategyRoute
  PricingRoute: typeof PricingRoute
  RankJumpPlanRoute: typeof RankJumpPlanRoute
  StudyDailyRoute: typeof StudyDailyRoute
  TimeManagementRoute: typeof TimeManagementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-mentor': {
      id: '/apply-mentor'
      path: '/apply-mentor'
      fullPath: '/apply-mentor'
      preLoaderRoute: typeof ApplyMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mocks-analysis': {
      id: '/mocks-analysis'
      path: '/mocks-analysis'
      fullPath: '/mocks-analysis'
      preLoaderRoute: typeof MocksAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plateaued-strategy': {
      id: '/plateaued-strategy'
      path: '/plateaued-strategy'
      fullPath: '/plateaued-strategy'
      preLoaderRoute: typeof PlateauedStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank-jump-plan': {
      id: '/rank-jump-plan'
      path: '/rank-jump-plan'
      fullPath: '/rank-jump-plan'
      preLoaderRoute: typeof RankJumpPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-daily': {
      id: '/study-daily'
      path: '/study-daily'
      fullPath: '/study-daily'
      preLoaderRoute: typeof StudyDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-management': {
      id: '/time-management'
      path: '/time-management'
      fullPath: '/time-management'
      preLoaderRoute: typeof TimeManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/': {
      id: '/mentors/'
      path: '/'
      fullPath: '/mentors/'
      preLoaderRoute: typeof MentorsIndexRouteImport
      parentRoute: typeof MentorsRoute
    }
    '/mentors/$mentorId': {
      id: '/mentors/$mentorId'
      path: '/$mentorId'
      fullPath: '/mentors/$mentorId'
      preLoaderRoute: typeof MentorsMentorIdRouteImport
      parentRoute: typeof MentorsRoute
    }
  }
}

interface MentorsRouteChildren {
  MentorsMentorIdRoute: typeof MentorsMentorIdRoute
  MentorsIndexRoute: typeof MentorsIndexRoute
}

const MentorsRouteChildren: MentorsRouteChildren = {
  MentorsMentorIdRoute: MentorsMentorIdRoute,
  MentorsIndexRoute: MentorsIndexRoute,
}

const MentorsRouteWithChildren =
  MentorsRoute._addFileChildren(MentorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyMentorRoute: ApplyMentorRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  MentorsRoute: MentorsRouteWithChildren,
  MocksAnalysisRoute: MocksAnalysisRoute,
  PlateauedStrategyRoute: PlateauedStrategyRoute,
  PricingRoute: PricingRoute,
  RankJumpPlanRoute: RankJumpPlanRoute,
  StudyDailyRoute: StudyDailyRoute,
  TimeManagementRoute: TimeManagementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
